Repository bellshade/Java, pull requests merged in 2021-10, with the labels that each got.

#1 add: Menambahkan Folder Hackerrank dan algoritma baru
  HackkerRank/JavaDatatypes.java
  HackkerRank/JavaIfElse.java
  HackkerRank/JavaLoops1.java
  HackkerRank/JavaLoops2.java
  HackkerRank/JavaStdinAndStdout2.java
  HackkerRank/JavaStdinAndStdoutI.java
  HackkerRank/WelcomeToJava.java
Labels: enhancement

#5 add: topik recursive function
  advanced/Recursive/Recursive.java
Labels: documentation, enhancement

#22 add: menambahkan algoritma DoWhile pada folder BasicLooping
  basic/BasicLooping/DoWhile.java
  basic/BasicLooping/README.md
Labels: documentation, enhancement

#9 docs: enhance docs
  .gitignore
  CONTRIBUTING.md
Labels: documentation, enhancement

#10 add: menambahkan konversi bilangan desimal ke biner
  conversion/DecimalToBinary.java
Labels: enhancement

#50 feat: algoritma mengubah oktal ke desimal
  conversion/OctalToDecimal.java
Labels: ready-to-merge, enhancement, java files, request tim java untuk review

#51 feat: menambahkan java abstrak
  intermediate/JavaAbstrac/README.md
  intermediate/JavaAbstrac/abstrakTutorial.java
Labels: ready-to-merge, enhancement, java files, request tim java untuk review, markdown files, request docs team untuk review
