Repository bellshade/Java, pull requests merged in 2022-03, with the labels that each got.

#100 feat: menambhkan materi graf pada java
  algorithm/data-structure/Graph/ContohGraph.java
  algorithm/data-structure/Graph/README.md
  algorithm/data-structure/Graph/assets/u_graf.png
Labels: ready-to-merge, enhancement, java files, markdown files, request tim java untuk review, sudah direview!

#101 feat: menambahkan materi switch lambda & yield
  learn/basic/StrukturKontrol/SwitchLambda/README.md
  learn/basic/StrukturKontrol/SwitchLambda/SwitchLambda.java
  learn/basic/StrukturKontrol/SwitchYield/README.md
  learn/basic/StrukturKontrol/SwitchYield/SwitchYield.java
Labels: ready-to-merge, enhancement, java files, markdown files, request tim java untuk review, sudah direview!

#103 Menambahkan action untuk test build project maven java
  .github/workflows/build.yml
Labels: ready-to-merge, sudah direview!

#105 docs: perbaikan typo dokumentasi README
  README.md
Labels: ready-to-merge, documentation, markdown files, sudah direview!

#106 docs: Menambahkan Dokumentasi
  .github/ISSUE_TEMPLATE/feature_report.md
  .github/pull_request_template.md
Labels: documentation, markdown files
